services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - 127.0.0.1:8000:8000
    restart: always

  api-server:
    build:
      context: ./api
      target: prod
    env_file:
      - .env
    restart: always
    volumes:
      - type: bind
        source: ./tmp
        target: /tmp
